# While the Docker images themselves are supported for production usage,
# this docker-compose.yaml is designed to be used by developers to run
# an environment locally. It is not designed to be used in production.
# We recommend to use Kubernetes in production with our Helm Charts:
# https://docs.camunda.io/docs/self-managed/setup/install/
# For local development, we recommend using KIND instead of `docker-compose`:
# https://docs.camunda.io/docs/self-managed/platform-deployment/helm-kubernetes/guides/local-kubernetes-cluster/

# This is a lightweight configuration with Zeebe, Operate, Tasklist, Connectors, and Elasticsearch

x-common-variables:
  CAMUNDA_ZEEBE_VERSION: 8.7.0
  CAMUNDA_OPERATE_VERSION: 8.7.0
  CAMUNDA_TASKLIST_VERSION: 8.7.0
  CAMUNDA_CONNECTORS_VERSION: 8.7.0

services:
  zeebe:
    image: camunda/zeebe:${CAMUNDA_ZEEBE_VERSION}
    container_name: zeebe
    ports:
      - "26500:26500"
      - "9600:9600"
      - "8088:8080"
    environment:
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_CLASSNAME=io.camunda.zeebe.exporter.ElasticsearchExporter
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_URL=http://elasticsearch:9200
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_BULK_SIZE=1
      - ZEEBE_AUTHENTICATION_ENABLED=false
      - ZEEBE_GATEWAY_SECURITY_ENABLED=false
      - ZEEBE_BROKER_DATA_DISKUSAGECOMMANDWATERMARK=0.998
      - ZEEBE_BROKER_DATA_DISKUSAGEREPLICATIONWATERMARK=0.999
      - CAMUNDA_DATABASE_URL=http://elasticsearch:9200
      - "JAVA_TOOL_OPTIONS=-Xms512m -Xmx512m"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "timeout 10s bash -c ':> /dev/tcp/127.0.0.1/9600' || exit 1" ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - zeebe:/usr/local/zeebe/data
    networks:
      - camunda-platform

  operate:
    image: camunda/operate:${CAMUNDA_OPERATE_VERSION}
    container_name: operate
    ports:
      - "8181:8080"
    environment:
      - JAVA_OPTS=-Dspring.profiles.active=operate,standalone -Dspring.profiles.exclude=auth -Dorg.apache.http.client5.auth.preemptive.BasicAuthentication=false -Dhttpclient.preemptive-authentication=false -Dspring.security.enabled=false
      - JAVA_OPTS=-Dspring.profiles.active=operate,standalone -Dspring.profiles.exclude=auth -Dspring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration,org.springframework.boot.autoconfigure.security.oauth2.client.servlet.OAuth2ClientAutoConfiguration,org.springframework.boot.autoconfigure.security.oauth2.resource.servlet.OAuth2ResourceServerAutoConfiguration,org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration -Dorg.apache.http.client5.auth.preemptive.BasicAuthentication=false -Dhttpclient.preemptive-authentication=false -Dspring.security.enabled=false -Dcamunda.operate.auth.enabled=false
      - JAVA_OPTS=-Dspring.profiles.active=operate,standalone -Dspring.profiles.exclude=auth -Dorg.apache.http.client5.auth.preemptive.BasicAuthentication=false -Dhttpclient.preemptive-authentication=false
      - CAMUNDA_OPERATE_ZEEBE_GATEWAYADDRESS=zeebe:26500
      - CAMUNDA_OPERATE_ELASTICSEARCH_URL=http://elasticsearch:9200
      - CAMUNDA_OPERATE_ZEEBEELASTICSEARCH_URL=http://elasticsearch:9200
      - CAMUNDA_OPERATE_AUTH_ENABLED=false
      - CAMUNDA_OPERATE_IDENTITY_AUTH_ENABLED=false
      - SPRING_SECURITY_ENABLED=false
      - CAMUNDA_SECURITY_ENABLED=false
      - CAMUNDA_IDENTITY_ENABLED=false
      - CAMUNDA_OPERATE_IDENTITY_URL=disabled
      - KEYCLOAK_ENABLED=false
      - CAMUNDA_OPERATE_CSRFPREVENTIONENABLED=false
      - CAMUNDA_OPERATE_CORS_ENABLED=true
      - SPRING_PROFILES_ACTIVE=operate,standalone
      - SPRING_PROFILES_EXCLUDE=auth
      - logging.level.org.springframework.boot.context.config=DEBUG
      - logging.level.io.camunda.application=DEBUG 
      - SPRING_AUTOCONFIGURE_EXCLUDE=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration,org.springframework.boot.autoconfigure.security.oauth2.client.servlet.OAuth2ClientAutoConfiguration,org.springframework.boot.autoconfigure.security.oauth2.resource.servlet.OAuth2ResourceServerAutoConfiguration
      - management.endpoints.web.exposure.include=health
      - management.endpoint.health.probes.enabled=true
      - CAMUNDA_OPERATE_SECURITY_AUTHENTICATION=none
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_ENABLED=false
      - SPRING_SECURITY_OAUTH2_RESOURCE_SERVER_ENABLED=false
      - CAMUNDA_OPERATE_ELASTICSEARCH_AUTH_ENABLED=false
      - logging.level.org.springframework=TRACE
      - logging.level.io.camunda=TRACE
      - logging.level.root=DEBUG
    volumes:
      - ./operate-security-killswitch.properties:/camunda/configuration/application.properties
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health/readiness"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - camunda-platform
    depends_on:
      - zeebe
      - elasticsearch

  tasklist:
    image: camunda/tasklist:${CAMUNDA_TASKLIST_VERSION}
    container_name: tasklist
    ports:
      - "8182:8080"
    environment:
      - JAVA_OPTS=-Dspring.profiles.active=tasklist,standalone -Dspring.profiles.exclude=auth -Dorg.apache.http.client5.auth.preemptive.BasicAuthentication=false -Dhttpclient.preemptive-authentication=false -Dspring.security.enabled=false
      - CAMUNDA_TASKLIST_ZEEBE_GATEWAYADDRESS=zeebe:26500
      - CAMUNDA_TASKLIST_ZEEBE_RESTADDRESS=http://zeebe:8080
      - CAMUNDA_TASKLIST_ELASTICSEARCH_URL=http://elasticsearch:9200
      - CAMUNDA_TASKLIST_ZEEBEELASTICSEARCH_URL=http://elasticsearch:9200
      - CAMUNDA_TASKLIST_AUTH_ENABLED=false
      - CAMUNDA_TASKLIST_IDENTITY_AUTH_ENABLED=false
      - SPRING_SECURITY_ENABLED=false
      - CAMUNDA_SECURITY_ENABLED=false
      - CAMUNDA_IDENTITY_ENABLED=false
      - CAMUNDA_TASKLIST_IDENTITY_URL=disabled
      - KEYCLOAK_ENABLED=false
      - CAMUNDA_TASKLIST_CSRFPREVENTIONENABLED=false
      - CAMUNDA_TASKLIST_CORS_ENABLED=true
      - SPRING_PROFILES_ACTIVE=tasklist,standalone
      - SPRING_PROFILES_EXCLUDE=auth
      - JAVA_OPTS=-Dspring.profiles.active=tasklist,standalone -Dspring.profiles.exclude=auth -Dorg.apache.http.client5.auth.preemptive.BasicAuthentication=false -Dhttpclient.preemptive-authentication=false
      - SPRING_AUTOCONFIGURE_EXCLUDE=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration,org.springframework.boot.autoconfigure.security.oauth2.client.servlet.OAuth2ClientAutoConfiguration,org.springframework.boot.autoconfigure.security.oauth2.resource.servlet.OAuth2ResourceServerAutoConfiguration
      - management.endpoints.web.exposure.include=health
      - management.endpoint.health.probes.enabled=true
      - CAMUNDA_TASKLIST_SECURITY_AUTHENTICATION=none
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_ENABLED=false
      - SPRING_SECURITY_OAUTH2_RESOURCE_SERVER_ENABLED=false
      - CAMUNDA_TASKLIST_ELASTICSEARCH_AUTH_ENABLED=false
      - logging.level.org.springframework=TRACE
      - logging.level.io.camunda=TRACE
      - logging.level.root=DEBUG
    volumes:
      - ./tasklist-security-killswitch.properties:/camunda/configuration/application.properties
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health/readiness"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - camunda-platform
    depends_on:
      - zeebe
      - elasticsearch

  connectors:
    image: camunda/connectors-bundle:${CAMUNDA_CONNECTORS_VERSION}
    container_name: connectors
    ports:
      - "8085:8080"
    environment:
      - CAMUNDA_CLIENT_MODE=self-managed
      - CAMUNDA_CLIENT_ZEEBE_GRPCADDRESS=http://zeebe:26500
      - OPERATE_CLIENT_BASEURL=http://operate:8080
      - OPERATE_CLIENT_PROFILE=simple
      - management.endpoints.web.exposure.include=health
      - management.endpoint.health.probes.enabled=true
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health/readiness"]
      interval: 30s
      timeout: 1s
      retries: 5
      start_period: 30s
    env_file: connector-secrets.txt
    networks:
      - camunda-platform
    depends_on:
      - zeebe
      - operate
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data
    networks:
      - camunda-platform

volumes:
  zeebe:
  es-data:

networks:
  camunda-platform:
    driver: bridge