# While the Docker images themselves are supported for production usage,
# this docker-compose.yaml is designed to be used by developers to run
# an environment locally. It is not designed to be used in production.
# We recommend to use Kubernetes in production with our Helm Charts:
# https://docs.camunda.io/docs/self-managed/setup/install/
# For local development, we recommend using KIND instead of `docker-compose`:
# https://docs.camunda.io/docs/self-managed/platform-deployment/helm-kubernetes/guides/local-kubernetes-cluster/

# This is a lightweight configuration with Zeebe, Operate, Tasklist, and Elasticsearch
# See docker-compose.yml for a configuration that also includes Optimize, Identity, and Keycloak.

services:

  zeebe: # https://docs.camunda.io/docs/self-managed/platform-deployment/docker/#zeebe
    image: camunda/zeebe:${CAMUNDA_ZEEBE_VERSION}
    container_name: zeebe
    ports:
      - "26500:26500"
      - "9600:9600"
      - "8088:8080"
    environment: # https://docs.camunda.io/docs/self-managed/zeebe-deployment/configuration/environment-variables/
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_CLASSNAME=io.camunda.zeebe.exporter.ElasticsearchExporter
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_URL=http://elasticsearch:9200
      # default is 1000, see here: https://github.com/camunda/zeebe/blob/main/exporters/elasticsearch-exporter/src/main/java/io/camunda/zeebe/exporter/ElasticsearchExporterConfiguration.java#L259
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_BULK_SIZE=1
      - ZEEBE_AUTHENTICATION_ENABLED=false
      - ZEEBE_GATEWAY_SECURITY_ENABLED=false
      # allow running with low disk space
      - ZEEBE_BROKER_DATA_DISKUSAGECOMMANDWATERMARK=0.998
      - ZEEBE_BROKER_DATA_DISKUSAGEREPLICATIONWATERMARK=0.999
      - CAMUNDA_DATABASE_URL=http://elasticsearch:9200
      - "JAVA_TOOL_OPTIONS=-Xms512m -Xmx512m"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "timeout 10s bash -c ':> /dev/tcp/127.0.0.1/9600' || exit 1" ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - zeebe:/usr/local/zeebe/data
    networks:
      - camunda-platform

  operate: # https://docs.camunda.io/docs/self-managed/platform-deployment/docker/#operate
    image: camunda/operate:${CAMUNDA_OPERATE_VERSION}
    container_name: operate
    ports:
      - "8181:8080"
    volumes:
      - C:/Users/diang/Desktop/docker-compose-8.7/operate-security-killswitch.properties:/camunda/configuration/application.properties
    environment: # https://docs.camunda.io/docs/self-managed/operate-deployment/configuration/
      - CAMUNDA_OPERATE_ZEEBE_GATEWAYADDRESS=zeebe:26500
      - CAMUNDA_OPERATE_ELASTICSEARCH_URL=http://elasticsearch:9200
      - CAMUNDA_OPERATE_ZEEBEELASTICSEARCH_URL=http://elasticsearch:9200
      - CAMUNDA_BPM_WEBAPP_UI_AUTHENTICATION_ENABLED=false
       # 禁用所有认证
      - CAMUNDA_OPERATE_AUTH_ENABLED=false
      - CAMUNDA_OPERATE_IDENTITY_AUTH_ENABLED=false
      - SPRING_SECURITY_OAUTH2_ENABLED=false
      - SPRING_SECURITY_ENABLED=false
      - CAMUNDA_IDENTITY_AUTH_ENABLED=false
        # 禁用 CSRF 和 CORS 限制（开发环境）
      - CAMUNDA_OPERATE_CSRFPREVENTIONENABLED=false
      - CAMUNDA_OPERATE_CORS_ENABLED=true
       # 强制覆盖 Spring Boot 的 auth profile
      - SPRING_PROFILES_ACTIVE=operate,standalone  # 移除 "auth"
       # 新增以下配置
      - KEYCLOAK_AUTH_ENABLED=false
      - KEYCLOAK_ENABLED=false
      - CAMUNDA_WEBAPPS_SECURITY_ENABLED=false
      - SERVER_SERVLET_SESSION_ENABLED=false
      - CAMUNDA_IDENTITY_ENABLED=false
      - CAMUNDA_OPERATE_IDENTITY_URL=disabled
      # 核武器级认证禁用
      - CAMUNDA_SECURITY_ENABLED=false
      # 禁用所有安全相关配置
      - MANAGEMENT_SECURITY_ENABLED=false
      - SERVER_SSL_ENABLED=false
      - SPRING_AUTOCONFIGURE_EXCLUDE=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
       # 新增以下配置
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=*

      - CAMUNDA_DATABASE_URL=http://elasticsearch:9200
      - management.endpoints.web.exposure.include=health
      - management.endpoint.health.probes.enabled=true
    healthcheck:
      test: [ "CMD-SHELL", "wget -O - -q 'http://localhost:9600/actuator/health/readiness'" ]
      interval: 30s
      timeout: 1s
      retries: 5
      start_period: 30s
    networks:
      - camunda-platform
    depends_on:
      - zeebe

  tasklist: # https://docs.camunda.io/docs/self-managed/platform-deployment/docker/#tasklist
    image: camunda/tasklist:${CAMUNDA_TASKLIST_VERSION}
    container_name: tasklist
    ports:
      - "8182:8080"
    environment: # https://docs.camunda.io/docs/self-managed/tasklist-deployment/configuration/
      - CAMUNDA_TASKLIST_ZEEBE_GATEWAYADDRESS=zeebe:26500
      - CAMUNDA_TASKLIST_ZEEBE_RESTADDRESS=http://zeebe:8080
      - CAMUNDA_TASKLIST_ELASTICSEARCH_URL=http://elasticsearch:9200
      - CAMUNDA_TASKLIST_ZEEBEELASTICSEARCH_URL=http://elasticsearch:9200
      - CAMUNDA_BPM_WEBAPP_UI_AUTHENTICATION_ENABLED=false
       # 禁用所有认证
      - CAMUNDA_TASKLIST_AUTH_ENABLED=false
      - CAMUNDA_TASKLIST_IDENTITY_AUTH_ENABLED=false
      - SPRING_SECURITY_OAUTH2_ENABLED=false
      - SPRING_SECURITY_ENABLED=false
      - CAMUNDA_IDENTITY_AUTH_ENABLED=false
        # 禁用 CSRF 和 CORS 限制（开发环境）
      - CAMUNDA_TASKLIST_CSRFPREVENTIONENABLED=false
      - CAMUNDA_TASKLIST_CORS_ENABLED=true
       # 强制覆盖 Spring Boot 的 auth profile
      - SPRING_PROFILES_ACTIVE=tasklist,standalone  # 移除 "auth"
       # 新增以下配置
      - KEYCLOAK_AUTH_ENABLED=false
      - KEYCLOAK_ENABLED=false
      - CAMUNDA_WEBAPPS_SECURITY_ENABLED=false
      - SERVER_SERVLET_SESSION_ENABLED=false
      - CAMUNDA_IDENTITY_ENABLED=false
      - CAMUNDA_TASKLIST_IDENTITY_URL=disabled
       # 核武器级认证禁用
      - CAMUNDA_SECURITY_ENABLED=false
      # 禁用所有安全相关配置
      - MANAGEMENT_SECURITY_ENABLED=false
      - SERVER_SSL_ENABLED=false
      - SPRING_AUTOCONFIGURE_EXCLUDE=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
    
      - CAMUNDA_DATABASE_URL=http://elasticsearch:9200
      - management.endpoints.web.exposure.include=health
      - management.endpoint.health.probes.enabled=true
    healthcheck:
      test: [ "CMD-SHELL", "wget -O - -q 'http://localhost:9600/actuator/health/readiness'" ]
      interval: 30s
      timeout: 1s
      retries: 5
      start_period: 30s
    networks:
      - camunda-platform
    depends_on:
      - zeebe

  connectors: # https://docs.camunda.io/docs/components/integration-framework/connectors/out-of-the-box-connectors/available-connectors-overview/
    image: camunda/connectors-bundle:${CAMUNDA_CONNECTORS_VERSION}
    container_name: connectors
    ports:
      - "8085:8080"
    environment:
      - CAMUNDA_CLIENT_MODE=self-managed
      - CAMUNDA_CLIENT_ZEEBE_GRPCADDRESS=http://zeebe:26500
      - OPERATE_CLIENT_BASEURL=http://operate:8080
      - OPERATE_CLIENT_PROFILE=simple
      - management.endpoints.web.exposure.include=health
      - management.endpoint.health.probes.enabled=true
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/actuator/health/readiness" ]
      interval: 30s
      timeout: 1s
      retries: 5
      start_period: 30s
    env_file: connector-secrets.txt
    networks:
      - camunda-platform
    depends_on:
      - zeebe
      - operate


volumes:
  zeebe:

networks:
  camunda-platform:
    external: true